spring:
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:43306/sample
    username: root
    password: root

  batch:
    job:
      # disabled job run at startup
      enabled: false
